




.build/pro328/src/simple_sender.cpp : src/simple_sender.ino
	@mkdir -p .build/pro328/src
	@echo [93msrc/simple_sender.ino[0m
	@/usr/bin/ino preproc  -o $@ $^


all : .build/pro328/src/simple_sender.cpp
	@true

