























.build/pro328/u2/u2.o : lib/u2/u2.cpp
	@echo [93mu2/u2.cpp[0m
	@mkdir -p .build/pro328/u2
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/u2/u2.cpp
include .build/pro328/u2/u2.d



.build/pro328/u2/libu2.a : .build/pro328/u2/u2.o
	@echo [92mLinking libu2.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/CallMe/CallMe.o : lib/CallMe/CallMe.cpp
	@echo [93mCallMe/CallMe.cpp[0m
	@mkdir -p .build/pro328/CallMe
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/CallMe/CallMe.cpp
include .build/pro328/CallMe/CallMe.d



.build/pro328/CallMe/libCallMe.a : .build/pro328/CallMe/CallMe.o
	@echo [92mLinking libCallMe.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/ISend/ISend.o : lib/ISend/ISend.cpp
	@echo [93mISend/ISend.cpp[0m
	@mkdir -p .build/pro328/ISend
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/ISend/ISend.cpp
include .build/pro328/ISend/ISend.d



.build/pro328/ISend/libISend.a : .build/pro328/ISend/ISend.o
	@echo [92mLinking libISend.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/MsTimer2/MsTimer2.o : lib/MsTimer2/MsTimer2.cpp
	@echo [93mMsTimer2/MsTimer2.cpp[0m
	@mkdir -p .build/pro328/MsTimer2
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/MsTimer2/MsTimer2.cpp
include .build/pro328/MsTimer2/MsTimer2.d



.build/pro328/MsTimer2/libMsTimer2.a : .build/pro328/MsTimer2/MsTimer2.o
	@echo [92mLinking libMsTimer2.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/IReceive/IReceive.o : lib/IReceive/IReceive.cpp
	@echo [93mIReceive/IReceive.cpp[0m
	@mkdir -p .build/pro328/IReceive
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/IReceive/IReceive.cpp
include .build/pro328/IReceive/IReceive.d



.build/pro328/IReceive/libIReceive.a : .build/pro328/IReceive/IReceive.o
	@echo [92mLinking libIReceive.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/SoftTimer/SoftTimer.o : lib/SoftTimer/SoftTimer.cpp
	@echo [93mSoftTimer/SoftTimer.cpp[0m
	@mkdir -p .build/pro328/SoftTimer
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/SoftTimer/SoftTimer.cpp
include .build/pro328/SoftTimer/SoftTimer.d



.build/pro328/SoftTimer/libSoftTimer.a : .build/pro328/SoftTimer/SoftTimer.o
	@echo [92mLinking libSoftTimer.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/Task/Task.o : lib/Task/Task.cpp
	@echo [93mTask/Task.cpp[0m
	@mkdir -p .build/pro328/Task
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/Task/Task.cpp
include .build/pro328/Task/Task.d



.build/pro328/Task/libTask.a : .build/pro328/Task/Task.o
	@echo [92mLinking libTask.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/comm/comm.o : lib/comm/comm.cpp
	@echo [93mcomm/comm.cpp[0m
	@mkdir -p .build/pro328/comm
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/comm/comm.cpp
include .build/pro328/comm/comm.d



.build/pro328/comm/libcomm.a : .build/pro328/comm/comm.o
	@echo [92mLinking libcomm.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/user_activity/user_activity.o : lib/user_activity/user_activity.cpp
	@echo [93muser_activity/user_activity.cpp[0m
	@mkdir -p .build/pro328/user_activity
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/user_activity/user_activity.cpp
include .build/pro328/user_activity/user_activity.d



.build/pro328/user_activity/libuser_activity.a : .build/pro328/user_activity/user_activity.o
	@echo [92mLinking libuser_activity.a[0m
	@/usr/bin/avr-ar rcs $@ $^












.build/pro328/rfm73/rfm73.o : lib/rfm73/rfm73.cpp
	@echo [93mrfm73/rfm73.cpp[0m
	@mkdir -p .build/pro328/rfm73
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c lib/rfm73/rfm73.cpp
include .build/pro328/rfm73/rfm73.d



.build/pro328/rfm73/librfm73.a : .build/pro328/rfm73/rfm73.o
	@echo [92mLinking librfm73.a[0m
	@/usr/bin/avr-ar rcs $@ $^







.build/pro328/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
	@echo [93marduino/wiring_digital.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c
include .build/pro328/arduino/wiring_digital.d

.build/pro328/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
	@echo [93marduino/wiring_analog.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c
include .build/pro328/arduino/wiring_analog.d

.build/pro328/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo [93marduino/wiring_pulse.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/pro328/arduino/wiring_pulse.d

.build/pro328/arduino/wiring.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
	@echo [93marduino/wiring.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c
include .build/pro328/arduino/wiring.d

.build/pro328/arduino/avr-libc/malloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
	@echo [93marduino/avr-libc/malloc.c[0m
	@mkdir -p .build/pro328/arduino/avr-libc
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/malloc.c
include .build/pro328/arduino/avr-libc/malloc.d

.build/pro328/arduino/avr-libc/realloc.o : /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
	@echo [93marduino/avr-libc/realloc.c[0m
	@mkdir -p .build/pro328/arduino/avr-libc
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/avr-libc/realloc.c
include .build/pro328/arduino/avr-libc/realloc.d

.build/pro328/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
	@echo [93marduino/wiring_shift.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c
include .build/pro328/arduino/wiring_shift.d

.build/pro328/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
	@echo [93marduino/WInterrupts.c[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c
include .build/pro328/arduino/WInterrupts.d






.build/pro328/arduino/WString.o : /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
	@echo [93marduino/WString.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp
include .build/pro328/arduino/WString.d

.build/pro328/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
	@echo [93marduino/USBCore.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp
include .build/pro328/arduino/USBCore.d

.build/pro328/arduino/Stream.o : /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
	@echo [93marduino/Stream.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp
include .build/pro328/arduino/Stream.d

.build/pro328/arduino/CDC.o : /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
	@echo [93marduino/CDC.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp
include .build/pro328/arduino/CDC.d

.build/pro328/arduino/Print.o : /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
	@echo [93marduino/Print.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp
include .build/pro328/arduino/Print.d

.build/pro328/arduino/new.o : /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
	@echo [93marduino/new.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp
include .build/pro328/arduino/new.d

.build/pro328/arduino/main.o : /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
	@echo [93marduino/main.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp
include .build/pro328/arduino/main.d

.build/pro328/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo [93marduino/HardwareSerial.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/pro328/arduino/HardwareSerial.d

.build/pro328/arduino/HID.o : /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
	@echo [93marduino/HID.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp
include .build/pro328/arduino/HID.d

.build/pro328/arduino/WMath.o : /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
	@echo [93marduino/WMath.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp
include .build/pro328/arduino/WMath.d

.build/pro328/arduino/Tone.o : /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
	@echo [93marduino/Tone.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp
include .build/pro328/arduino/Tone.d

.build/pro328/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo [93marduino/IPAddress.cpp[0m
	@mkdir -p .build/pro328/arduino
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/pro328/arduino/IPAddress.d



.build/pro328/arduino/libarduino.a : .build/pro328/arduino/wiring_digital.o .build/pro328/arduino/wiring_analog.o .build/pro328/arduino/wiring_pulse.o .build/pro328/arduino/wiring.o .build/pro328/arduino/avr-libc/malloc.o .build/pro328/arduino/avr-libc/realloc.o .build/pro328/arduino/wiring_shift.o .build/pro328/arduino/WInterrupts.o .build/pro328/arduino/WString.o .build/pro328/arduino/USBCore.o .build/pro328/arduino/Stream.o .build/pro328/arduino/CDC.o .build/pro328/arduino/Print.o .build/pro328/arduino/new.o .build/pro328/arduino/main.o .build/pro328/arduino/HardwareSerial.o .build/pro328/arduino/HID.o .build/pro328/arduino/WMath.o .build/pro328/arduino/Tone.o .build/pro328/arduino/IPAddress.o
	@echo [92mLinking libarduino.a[0m
	@/usr/bin/avr-ar rcs $@ $^















.build/pro328/src/simple_sender.o : .build/pro328/src/simple_sender.cpp
	@echo [93msrc/simple_sender.cpp[0m
	@mkdir -p .build/pro328/src
	@/usr/lib64/ccache/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=8000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -Ilib/u2 -Ilib/CallMe -Ilib/ISend -Ilib/MsTimer2 -Ilib/IReceive -Ilib/SoftTimer -Ilib/Task -Ilib/comm -Ilib/user_activity -Ilib/rfm73 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/cores/arduino/avr-libc -fno-exceptions -iquote src  -o $@ -c .build/pro328/src/simple_sender.cpp
include .build/pro328/src/simple_sender.d







.build/pro328/firmware.elf : .build/pro328/src/simple_sender.o .build/pro328/u2/libu2.a .build/pro328/CallMe/libCallMe.a .build/pro328/ISend/libISend.a .build/pro328/MsTimer2/libMsTimer2.a .build/pro328/IReceive/libIReceive.a .build/pro328/SoftTimer/libSoftTimer.a .build/pro328/Task/libTask.a .build/pro328/comm/libcomm.a .build/pro328/user_activity/libuser_activity.a .build/pro328/rfm73/librfm73.a .build/pro328/arduino/libarduino.a
	@echo [92mLinking firmware.elf[0m
	@/usr/lib64/ccache/avr-gcc -Os -Wl,--gc-sections -mmcu=atmega328p -o $@ $^ -lm


.build/pro328/firmware.hex : .build/pro328/firmware.elf
	@echo [92mConverting to firmware.hex[0m
	@/usr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/pro328/src/dependencies.d .build/pro328/arduino/dependencies.d .build/pro328/user_activity/dependencies.d .build/pro328/u2/dependencies.d .build/pro328/Task/dependencies.d .build/pro328/CallMe/dependencies.d .build/pro328/comm/dependencies.d .build/pro328/rfm73/dependencies.d .build/pro328/SoftTimer/dependencies.d .build/pro328/MsTimer2/dependencies.d .build/pro328/IReceive/dependencies.d .build/pro328/ISend/dependencies.d

all : .build/pro328/firmware.hex
	@true

