#!/bin/bash
#功能：
#在指定的mk文件里面的指定行追加
#当前目录下面temp文件里面的内容。
#用法：mkt_appendlines 文件
if [ "$1" == "" ]; then
	echo "please input file"
	exit
fi

echo "mtk_appendlines \"文件名\""
echo $1
sed -i '/GN_MTK_BSP = yes/r temp' $1
