#!/bin/bash
#在下面三个字串开头的行追加字符串
#用法：mtk_appendtail <1 or 2 or 3>  字符串
KEY1="AUTO_ADD_GLOBAL_DEFINE_BY_NAME ="
KEY2="AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE ="
KEY3="AUTO_ADD_GLOBAL_DEFINE_BY_VALUE ="

echo "=========================="
echo "关键字:  $1[1 2 3]"
echo "追加字符串:   $2"
echo "文件名: $3"
echo
echo "=========================="

if [ "$1" == "" ] || [ "$2" == "" ] || [ "$3" == "" ]; then
	exit
fi

case "$1" in
1)
	sed -i -e '/'"$KEY1"'/s/$/ '"$2"'/' $3
	;;
2)
	sed -i -e '/'"$KEY2"'/s/$/ '"$2"'/' $3
	;;
3)
	sed -i -e '/'"$KEY3"'/s/$/ '"$2"'/' $3
	;;
*)
	break
	;;
esac
echo "ok, please check again!!!"
