#!/bin/bash

#important!!!!!!!!
#$1 config main dir
#$2 config main dir - sub prj dir

##############################
TAG="[mycheckout.sh]"
##############################

projectspath=`getitem.sh "$1/public" "projectspath"`
username=`getitem.sh "$1/public" "username"`
password=`getitem.sh "$1/public" "password"`
prj_config_file="$1/$2/$2"

##############################################

if [ ! -d $projectspath ]; then
	mkdir -p $projectspath
fi

if [ ! -f "$prj_config_file" ]; then
	echo "can not find configs exit!!!!!!!!"
	exit
fi
android=`getitem.sh "$prj_config_file" "android"`
package=`getitem.sh "$prj_config_file" "package"`
project=`getitem.sh "$prj_config_file" "project"`
switch=`getitem.sh "$prj_config_file" "switch"`

if [[ "$switch" == "off" ]]; then
	echo "$TAG:switch is off"
	exit
fi

if [[ "$project" == "" ]]; then 
	echo "$TAG:project is nothing"
	exit
fi

prjdirnametemp=$(echo $android | sed 's/http:\/\/192.168.110.97\///g'| sed 's/\//_/g')

buildmode=`getitem.sh "$prj_config_file" "buildmode"`
if [[ "$buildmode" == "user" ]]; then
	prjdirname=$project-$prjdirnametemp-`date +%Y%m%d_%H%M_%w-"user"`
else
	prjdirname=$project-$prjdirnametemp-`date +%Y%m%d_%H%M_%w-"eng"`
fi

	if [ -d "$projectspath" ]; then
		cd $projectspath
	else
		mkdir -p $projectspath
		if [ ! -d "$projectspath" ]; then
			echo "$TAG:can not create the projects dir"
			exit
		fi
		cd $projectspath
	fi

	rm -rf $prjdirname
	mkdir $prjdirname
	echo "$TAG:mkdir:"$prjdirname
	if [ ! -d $prjdirname ]; then
		echo "$TAG:mkdir $prjdirname error,exit"
		exit
	fi
	cd $prjdirname
	echo "$TAG:cd $prjdirname, pwd:$PWD"

	sys_name=$(echo $android | sed 's/\(.*\/\)\(.*\)/\2/')
	svn co -q "$android" "${sys_name}" --username "$username" --password="$password"
	app_name=$(echo $package | sed 's/\(.*svn\/\)\(.*\)\(\/.*\)/\2/' | sed 's/\(.*\)\(\/.*\)/\1/')
	svn co -q $package "${app_name}" --username "$username" --password="$password"
	if [ ! -d "$sys_name" ]; then
		echo "$TAG:not found "$sys_name" ,exit"
		exit
	fi

###### prj == NULL #####
if [[ "$project" == "NULL" ]] || [[ "$project" == "null" ]]; then
	echo "$TAG:project is "$project",exit"
	exit
fi
#####    end    #####


#####for review #####
	reviewoutput=`getitem.sh "$prj_config_file" "reviewoutput"`
	if [[ -d "$reviewoutput" ]]; then
		echo "reviewoutput="$reviewoutput"" >> prj_info
		echo "prjpath="${sys_name}"" >> prj_info 
		echo "project="$project"" >> prj_info 
	fi
#####    end   #####

	cd "$sys_name"
	echo "$TAG:cd $sys_name"
	echo "$TAG:cd $sys_name, pwd:$PWD"

database=`getitem.sh "$prj_config_file" "database"`
if [[ "$database" == "yes" ]] || [[ "$database" == "y" ]]; then
	echo "$TAG:${database}=yes"
	cscope -Rbq
	ctags -R
else
	echo "$TAG:${database}=no"
	cscope -Rbq
	ctags -R
fi

echo "$TAG:compile:$project"
buildmode=`getitem.sh "$prj_config_file" "buildmode"`
echo $buildmode
if [[ "$buildmode" == "user" ]]; then
	echo "$TAG:user"
	./makeMtk -o=TARGET_BUILD_VARIANT=user "$project" n
else
	echo "$TAG:eng"
	./makeMtk "$project" n
fi
#################################################################################3

package.sh "$PWD" "$prjdirname" "$android"

output=`getitem.sh "$prj_config_file" "output"`
if [[ "$output" != "" ]]; then
#add plugin:add release version into ftp
#paras: [compile directory] [prjdirname] [http] [out path]
	output.sh "$PWD" "$prjdirname" "$android" "$output"
#end
fi

bakoutput=`getitem.sh "$prj_config_file" "bakoutput"`
if [[ "$bakoutput" != "" ]]; then
#add plugin:add release version into ftp
#paras: [compile directory] [prjdirname] [http] [bakoutput path]
	bakoutput.sh "$PWD" "$prjdirname" "$android" "$bakoutput"
#end
fi

#add plugin:check compile result and flag the project dir 
	checkcompileresult.sh "$projectspath" "$prjdirname"
#end
